from enum import StrEnum


class MetricType(StrEnum):
    MONETARY_ABSOLUTE = "MONETARY_ABSOLUTE"
    MONETARY_PER_SHARE = "MONETARY_PER_SHARE"
    COUNT = "COUNT"
    PERCENTAGE = "PERCENTAGE"
    RATIO = "RATIO"
    RANK = "RANK"


class UnitScope(StrEnum):
    METRIC = "METRIC"
    ROW = "ROW"
    CELL = "CELL"
    COLUMN = "COLUMN"
    TABLE = "TABLE"
    STATEMENT = "STATEMENT"
    PAGE = "PAGE"
    REPORT = "REPORT"


class EntityScope(StrEnum):
    COMPANY = "COMPANY"
    BANK = "BANK"
    GROUP = "GROUP"
    CONSOLIDATED = "CONSOLIDATED"
    UNKNOWN = "UNKNOWN"


class PeriodType(StrEnum):
    QUARTER = "QUARTER"
    YTD = "YTD"
    FY = "FY"
    AS_AT = "AS_AT"


class MissingReason(StrEnum):
    NOT_REPORTED = "NOT_REPORTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    PENDING_FILING = "PENDING_FILING"
    NO_PRICE = "NO_PRICE"
    CONSOLIDATED_ONLY = "CONSOLIDATED_ONLY"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    UNIT_NOT_DETECTED = "UNIT_NOT_DETECTED"
    UNIT_CONFLICT = "UNIT_CONFLICT"
    ENTITY_SCOPE_AMBIGUOUS = "ENTITY_SCOPE_AMBIGUOUS"
    PERIOD_AMBIGUOUS = "PERIOD_AMBIGUOUS"
    METRIC_MAPPING_REQUIRED = "METRIC_MAPPING_REQUIRED"
    Q4_DERIVATION_INCOMPATIBLE = "Q4_DERIVATION_INCOMPATIBLE"
    EXACT_QUARTER_NOT_REPORTED = "EXACT_QUARTER_NOT_REPORTED"
    HISTORICAL_PRICE_NOT_AVAILABLE = "HISTORICAL_PRICE_NOT_AVAILABLE"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    BALANCE_SHEET_RECONCILIATION_FAILED = "BALANCE_SHEET_RECONCILIATION_FAILED"
    ZERO_EQUITY = "ZERO_EQUITY"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    SOURCE_CONFIRMED_NOT_REPORTED = "SOURCE_CONFIRMED_NOT_REPORTED"
    NOT_FOUND_BY_PARSER = "NOT_FOUND_BY_PARSER"
    CROSS_METRIC_CONTEXT_INCONSISTENT = "CROSS_METRIC_CONTEXT_INCONSISTENT"
    PERIOD_NOT_RESOLVED = "PERIOD_NOT_RESOLVED"
    ENTITY_NOT_RESOLVED = "ENTITY_NOT_RESOLVED"
    UNIT_NOT_RESOLVED = "UNIT_NOT_RESOLVED"
    INSUFFICIENT_INPUT = "INSUFFICIENT_INPUT"
    MISSING_DENOMINATOR = "MISSING_DENOMINATOR"
    NON_POSITIVE_DENOMINATOR = "NON_POSITIVE_DENOMINATOR"
    INCOMPATIBLE_SCOPE = "INCOMPATIBLE_SCOPE"
    INCOMPATIBLE_CURRENCY = "INCOMPATIBLE_CURRENCY"
    CROSS_FILING_MISMATCH = "CROSS_FILING_MISMATCH"
    CUMULATIVE_ONLY = "CUMULATIVE_ONLY"
    LOW_CERTAINTY = "LOW_CERTAINTY"
    COLUMN_AMBIGUOUS = "COLUMN_AMBIGUOUS"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    BALANCE_SHEET_SANITY_FAILED = "BALANCE_SHEET_SANITY_FAILED"
