"""Richer accounting ontology (Revision 2 §15). Maps concepts, not final 14 outputs."""

from __future__ import annotations

PROFIT_LOSS_CONCEPTS: tuple[str, ...] = (
    "TOP_LINE",
    "REVENUE",
    "GROSS_INCOME",
    "INTEREST_INCOME",
    "INTEREST_EXPENSE",
    "NET_INTEREST_INCOME",
    "FEE_INCOME",
    "TRADING_INCOME",
    "INSURANCE_REVENUE",
    "COST_OF_SALES",
    "GROSS_PROFIT",
    "OTHER_OPERATING_INCOME",
    "DISTRIBUTION_EXPENSE",
    "ADMINISTRATIVE_EXPENSE",
    "OTHER_OPERATING_EXPENSE",
    "IMPAIRMENT",
    "OPERATING_PROFIT",
    "FINANCE_INCOME",
    "FINANCE_COST",
    "ASSOCIATE_JV_RESULT",
    "PBT",
    "INCOME_TAX",
    "CONTINUING_OPERATIONS_RESULT",
    "DISCONTINUED_OPERATIONS_RESULT",
    "PAT",
    "ATTRIBUTION_OWNERS",
    "ATTRIBUTION_NCI",
    "EPS_BASIC",
    "EPS_DILUTED",
    "WEIGHTED_AVG_SHARES",
)

FINANCIAL_POSITION_CONCEPTS: tuple[str, ...] = (
    "NON_CURRENT_ASSETS",
    "CURRENT_ASSETS",
    "TOTAL_ASSETS",
    "SHARE_CAPITAL",
    "RESERVES",
    "EQUITY_ATTRIBUTABLE_TO_OWNERS",
    "NCI_EQUITY",
    "TOTAL_EQUITY",
    "NON_CURRENT_LIABILITIES",
    "CURRENT_LIABILITIES",
    "TOTAL_LIABILITIES",
    "ORDINARY_SHARES",
    "NAVPS",
)

# Target projection codes used by the 14-field publish contract.
TARGET_CONCEPT_MAP: dict[str, str] = {
    "PAT": "PAT",
    "PBT": "PBT",
    "EPS_BASIC": "EPS_BASIC",
    "EPS_DILUTED": "EPS_DILUTED",
    "NAVPS": "NAVPS",
    "OPERATING_PROFIT": "OPERATING_PROFIT",
    "TOTAL_EQUITY": "TOTAL_EQUITY",
    "TOTAL_ASSETS": "TOTAL_ASSETS",
    "TOTAL_LIABILITIES": "TOTAL_LIABILITIES",
    "TOP_LINE": "TOP_LINE",
    "REVENUE": "TOP_LINE",
    "GROSS_INCOME": "TOP_LINE",
}


def all_concepts() -> tuple[str, ...]:
    return PROFIT_LOSS_CONCEPTS + FINANCIAL_POSITION_CONCEPTS


CONCEPT_ALIASES: dict[str, tuple[str, ...]] = {
    "TOP_LINE": (
        "revenue",
        "net revenue",
        "gross income",
        "total operating income",
        "total income",
        "net operating income",
        "insurance revenue",
        "gross written premium",
        "net earned premium",
        "net sales",
        "total revenue",
        "turnover",
        "income",
        "interest income",
        "net interest income",
    ),
    "OPERATING_PROFIT": (
        "operating profit",
        "results from operating activities",
        "profit from operations",
        "profit from operation",
        "profit loss from operations",
        "operating profit before tax on financial services",
        "results of operating activities",
        "profit from operating activities",
        "results from operations",
        "result from operating activities",
        "ebit",
        "earnings before interest and tax",
    ),
    "PBT": (
        "profit before tax",
        "profit before taxation",
        "profit before income tax",
        "loss before tax",
        "loss before taxation",
    ),
    "PAT": (
        "profit for the period",
        "profit for the quarter",
        "profit after tax",
        "profit after taxation",
        "net profit after tax",
        "loss for the period",
        "net loss for the period",
        "net profit for the period",
        "profit attributable to equity holders",
        "profit attributable to owners of the company",
        "profit attributable to shareholders of the company",
    ),
    "INCOME_TAX": ("income tax", "taxation", "tax expense", "income tax expense"),
    "EPS_BASIC": (
        "basic earnings per share",
        "basic loss per share",
        "earnings per share basic",
        "basic diluted earnings per share",
        "earnings per ordinary share",
        "earning share",
    ),
    "EPS_DILUTED": (
        "diluted earnings per share",
        "diluted loss per share",
        "earnings per share diluted",
    ),
    "TOTAL_ASSETS": ("total assets",),
    "TOTAL_EQUITY": (
        "total equity",
        "total shareholders equity",
        "equity attributable to owners",
        "shareholders funds",
    ),
    "TOTAL_LIABILITIES": (
        "total liabilities",
        "total liability",
        "total equity and liabilities",
    ),
    "NAVPS": (
        "net asset value per share",
        "net assets per share",
        "nav per share",
        "net asset per share",
    ),
    "GROSS_PROFIT": ("gross profit",),
    "COST_OF_SALES": ("cost of sales", "cost of goods sold"),
    "CURRENT_LIABILITIES": ("current liabilities", "total current liabilities"),
    "NON_CURRENT_LIABILITIES": (
        "non-current liabilities",
        "non current liabilities",
        "total non-current liabilities",
    ),
    "CURRENT_ASSETS": ("current assets", "total current assets"),
    "NON_CURRENT_ASSETS": (
        "non-current assets",
        "non current assets",
        "total non-current assets",
    ),
}
